/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraComponent: typeof import('./src/components/CameraComponent.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    OnvifCameraComponent: typeof import('./src/components/OnvifCameraComponent.vue')['default']
    PTZControl: typeof import('./src/components/PTZControl.vue')['default']
    RemoteDesktopComponent: typeof import('./src/components/RemoteDesktopComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
